package com.chacha.presentation.booking.booking_destination_list

data class Place(
    val name: String,
    val pickupStations: String,
    val dropoffStations: String
)


 val places = listOf(
    Place("Mombasa", "Mombasa", "Nairobi"),
     Place("Changamwe", "Station 3", "Station 4"),
     Place("Voi","",""),
     Place("Nairobi","",""),
     Place("Narok","",""),
     Place("Sotik","",""),
     Place("Bomet","",""),
     Place("Kijauri","",""),
     Place("Keroka","",""),
     Place("Kisii","",""),
     Place("Nyanchenge","",""),
     Place("Birongo","",""),
     Place("Keumbu","",""),
     Place("Rongo","",""),
     Place("Tabaka","",""),
     Place("Awendo","",""),
     Place("Sirare","",""),
     Place("Kehancha","",""),
     Place("Rodi","",""),
     Place("Ndhiwa","",""),
     Place("Sori","",""),
     Place("Homabay","",""),
     Place("Mbita","",""),
     Place("Kendu Bay","",""),
     Place("Katito","",""),
     Place("Sondu","",""),
     Place("Oyugis","",""),
     Place("Nyamira","",""),
     Place("Ekerenyo","",""),
     Place("Nakuru","",""),
     Place("Kericho","",""),
     Place("Kisumu","",""),
     Place("Luanda","",""),
     Place("Maseno","",""),
     Place("Yala","",""),
     Place("Nyadorera","",""),
     Place("Siaya","",""),
     Place("Ugunja","",""),
     Place("Bumala","",""),
     Place("Busia","",""),
     Place("Rangwe","",""),
     Place("Kadongo","",""),
     Place("Ikonge","",""),
     Place("Nyakoe","",""),
     Place("Suneka","",""),
     Place("Kegogi","",""),
     Place("Kapsabet","",""),
     Place("Ahero","",""),
     Place("Majengo","",""),
     Place("Mbale","",""),
     Place("Kakamega","",""),
     Place("Mumias","",""),
     Place("Bungoma","",""),
     Place("Nambale","",""),
     Place("Chavakali","",""),
     Place("Kaimosi","",""),
     Place("Funyula","",""),
     Place("Kombewa","",""),
     Place("Por Victoria","",""),

    // Add more places as needed
)
